---
- name: stat timesyncd.conf
  stat:
    path: "/etc/systemd/timesyncd.conf"
  register: timesyncd_conf
- name: setup NTP servers
  lineinfile:
    dest: "/etc/systemd/timesyncd.conf"
    regexp: '^#?(NTP|Servers)=.*'
    line: '\1={{ timesyncd_ntp_servers | join(" ") }}'
    backrefs: yes
  when: timesyncd_conf.stat.exists
  notify:
    - timedatectl set-ntp true
